echo "Restarting Praxis Bot Services..."

start powershell cd "standalone-user-client" ; docker-compose restart ; cd ".."
start powershell cd "standalone-db" ; docker-compose restart ; cd ".."
start powershell cd "standalone-eventlog" ; docker-compose restart ; cd ".."
start powershell cd "standalone-command" ; docker-compose restart ; cd ".."
start powershell cd "standalone-channelrewards" ; docker-compose restart ; cd ".."
start powershell cd "standalone-lights" ; docker-compose restart ; cd ".."
start powershell cd "standalone-tts-core" ; docker-compose restart ; cd ".."
start powershell cd "standalone-websource" ; docker-compose restart ; cd ".."
start powershell cd "standalone-discord-script" ; docker-compose restart ; cd ".."
start powershell cd "standalone-twitch-script" ; docker-compose restart ; cd ".."
start powershell cd "standalone-twitch-pubsub" ; docker-compose restart ; cd ".."
