#!/bin/bash
cd "standalone-core"
docker-compose down
cd ".."
cd "standalone-user-client"
docker-compose down
cd ".."
cd "standalone-eventlog"
docker-compose down
cd ".."
cd "standalone-command"
docker-compose down
cd ".."
cd "standalone-channelrewards"
docker-compose down
cd ".."
cd "standalone-lights"
docker-compose down
cd ".."
cd "standalone-tts-core"
docker-compose down
cd ".."
cd "standalone-websource"
docker-compose down
cd ".."
cd "standalone-discord-script"
docker-compose down
cd ".."
cd "standalone-twitch-script"
docker-compose down
cd ".."
cd "standalone-twitch-pubsub"
docker-compose down
cd ".."