version: '3.7'
services:
  standalone_eventlog:
    image: standalone_eventlog
    ports:
      - 42008:42008
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
networks:
  praxisbot:
    name: praxisbot