version: '3.7'
services:
  standalone_command:
    image: standalone_command
    ports:
      - 42010:42010
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
    volumes:
      - "../stream_sources:/Praxis/stream_sources/"
      - "../logs:/Praxis/logs"
      - "../credentials:/Praxis/credentials"
networks:
  praxisbot:
    name: praxisbot