
services:
  standalone-tts-core:
    image: standalone-tts-core
    ports:
      - 42064:42064
    environment:
      - CONTAINER_NAME=standalone-tts-core
      - ISDOCKER=cat
    networks:
      - praxisbot
    volumes:
      - "../logs:/Praxis/logs"
      - "../credentials:/Praxis/credentials"
      - "../config.py:/Praxis/config.py"
networks:
  praxisbot:
    name: praxisbot