version: '3.7'
services:
  standalone_pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
     - 42099:80
    networks:
      - praxisbot
  standalone_db_main:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - ISDOCKER=cat
      - POSTGRES_DB=PRAXIS_BOT_DB
      - POSTGRES_USER=PRAXIS_BOT
      - POSTGRES_PASSWORD=PraxisPraxisPraxis
      - PGDATA=/Praxis/standalone_db/db_data
    volumes:
      - "./db_data:/Praxis/standalone_db/db_data"
      - "../logs:/Praxis/logs"
    networks:
      - praxisbot
  standalone_db_manager:
    image: standalone_db
    ports:
      - 42002:42002
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
    volumes:
      - "../logs:/Praxis/logs"
      - "../credentials:/Praxis/credentials"
networks:
  praxisbot:
    name: praxisbot