# Generated by Django 3.2.12 on 2022-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chyron_entry',
            name='allowedGroups',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='chyron_entry',
            name='allowedServices',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='chyron_entry',
            name='allowedUsers',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='chyron_entry',
            name='coolDownLength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chyron_entry',
            name='isRestricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='praxisbot_commands_v0_savedvariables',
            name='data',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
