# Generated by Django 3.2.12 on 2022-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220330_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraxisBot_UserGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PraxisBot_Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('randID', models.CharField(max_length=300)),
                ('nickname', models.CharField(max_length=300)),
                ('pin', models.CharField(blank=True, default='', max_length=300)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isMod', models.BooleanField(default=False)),
                ('groups', models.CharField(blank=True, default='', max_length=500)),
                ('isBanned', models.BooleanField(default=False)),
                ('isMuted', models.BooleanField(default=False)),
                ('isSubscriber', models.BooleanField(default=False)),
                ('isDonator', models.BooleanField(default=False)),
                ('isVIP', models.BooleanField(default=False)),
                ('discordID', models.CharField(blank=True, default='', max_length=300)),
                ('twitchID', models.CharField(blank=True, default='', max_length=300)),
                ('twitterID', models.CharField(blank=True, default='', max_length=300)),
                ('pgpPublicKey', models.TextField(blank=True, default='', max_length=16384)),
            ],
        ),
    ]
