# Generated by Django 3.2.12 on 2022-03-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_praxisbot_usergroups_praxisbot_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chyron_entry',
            name='allowedGroups',
        ),
        migrations.RemoveField(
            model_name='chyron_entry',
            name='allowedServices',
        ),
        migrations.RemoveField(
            model_name='chyron_entry',
            name='allowedUsers',
        ),
        migrations.RemoveField(
            model_name='chyron_entry',
            name='coolDownLength',
        ),
        migrations.RemoveField(
            model_name='chyron_entry',
            name='isRestricted',
        ),
        migrations.AddField(
            model_name='praxisbot_commands_v0',
            name='allowedGroups',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='praxisbot_commands_v0',
            name='allowedServices',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='praxisbot_commands_v0',
            name='allowedUsers',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='praxisbot_commands_v0',
            name='coolDownLength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='praxisbot_commands_v0',
            name='isRestricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='praxisbot_commands_v0',
            name='lastUsed',
            field=models.IntegerField(default=0),
        ),
    ]
