version: '3.7'
services:
  standalone_lights:
    image: standalone_lights
    ports:
      - 42042:42042
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
networks:
  praxisbot:
    name: praxisbot