version: '3.7'
services:
  standalone_twitch_script:
    image: standalone_twitch_script
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
networks:
  praxisbot:
    name: praxisbot