version: '3.7'
services:
  standalone_user_client:
    image: standalone_user_client
    ports:
      - 42055:42055
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
networks:
  praxisbot:
    name: praxisbot