
services:
  standalone-websource:
    image: standalone-websource
    ports:
      - 42012:42012
    environment:
      - CONTAINER_NAME=standalone-websource
      - ISDOCKER=cat
    networks:
      - praxisbot
    volumes:
      - "../logs:/Praxis/logs"
      - "../credentials:/Praxis/credentials"
      - "../config.py:/Praxis/config.py"
networks:
  praxisbot:
    name: praxisbot