version: '3.7'
services:
  standalone_channelrewards:
    image: standalone_channelrewards
    ports:
      - 42069:42069
    environment:
      - ISDOCKER=cat
    volumes:
      - "../logs:/Praxis/logs"