version: '3.7'
services:
  standalone_tts_core:
    image: standalone_tts_core
    ports:
      - 42064:42064
    environment:
      - ISDOCKER=cat
    networks:
      - praxisbot
networks:
  praxisbot:
    name: praxisbot